'use strict';
const $=id=>document.getElementById(id), cv=$('canvas'),ctx=cv.getContext('2d'),preview=$('preview').getContext('2d');
let state={w:32,h:32,pixels:Array(1024).fill(0),objects:[],mode:'pixel'}, tool='pencil', selected=-1, past=[],future=[],drag=null,cursor={x:0,y:0},keyboard=false;
const names={pencil:'畫筆',eraser:'橡皮擦',fill:'填色',line:'直線',rect:'矩形',ellipse:'橢圓',text:'文字',select:'選取'};
const icons={pencil:'✎',eraser:'▱',fill:'▨',line:'╱',rect:'□',ellipse:'○',text:'T',select:'↖'};
const clone=x=>JSON.parse(JSON.stringify(x));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function snapshot(){past.push(clone(state));if(past.length>60)past.shift();future=[];}
function history(back){let from=back?past:future,to=back?future:past;if(!from.length)return;to.push(clone(state));state=from.pop();selected=-1;sync()}
function put(p,x,y,c=1){x=Math.round(x);y=Math.round(y);if(x>=0&&y>=0&&x<state.w&&y<state.h)p[y*state.w+x]=c}
function line(p,x,y,ex,ey,c=1){let dx=Math.abs(ex-x),sx=x<ex?1:-1,dy=-Math.abs(ey-y),sy=y<ey?1:-1,e=dx+dy;for(let i=0;i<1000;i++){put(p,x,y,c);if(x===ex&&y===ey)break;const e2=2*e;if(e2>=dy){e+=dy;x+=sx}if(e2<=dx){e+=dx;y+=sy}}}
function rasterObject(p,o){const x=Math.min(o.x,o.ex),y=Math.min(o.y,o.ey),w=Math.abs(o.ex-o.x),h=Math.abs(o.ey-o.y);if(o.type==='line')line(p,o.x,o.y,o.ex,o.ey);else if(o.type==='rect'){if(o.filled){for(let j=y;j<=y+h;j++)for(let i=x;i<=x+w;i++)put(p,i,j)}else{line(p,x,y,x+w,y);line(p,x+w,y,x+w,y+h);line(p,x+w,y+h,x,y+h);line(p,x,y+h,x,y)}}else if(o.type==='ellipse'){if(!w||!h){line(p,x,y,x+w,y+h);return}const rx=w/2,ry=h/2,cx=x+rx,cy=y+ry;if(o.filled){for(let j=y;j<=y+h;j++)for(let i=x;i<=x+w;i++)if(((i-cx)/rx)**2+((j-cy)/ry)**2<=1)put(p,i,j)}else{let prev=null;for(let t=0;t<=Math.PI*2+.05;t+=.04){const pt={x:Math.round(cx+rx*Math.cos(t)),y:Math.round(cy+ry*Math.sin(t))};if(prev)line(p,prev.x,prev.y,pt.x,pt.y);prev=pt}}}else if(o.type==='text'){const c=document.createElement('canvas');c.width=state.w;c.height=state.h;const g=c.getContext('2d');g.fillStyle='white';const m=textMetrics(o.text,o.size,g);g.fillText(o.text,o.x+m.left,o.y+m.ascent);const data=g.getImageData(0,0,state.w,state.h).data;for(let i=0;i<p.length;i++)if(data[i*4+3]>100)p[i]=1}}
function composed(){const p=state.pixels.slice();state.objects.forEach(o=>rasterObject(p,o));return p}
function bounds(o){if(o.type==='text'){const m=textMetrics(o.text,o.size);return {x:o.x,y:o.y,w:m.w,h:m.h};}return{x:Math.min(o.x,o.ex),y:Math.min(o.y,o.ey),w:Math.abs(o.ex-o.x)+1,h:Math.abs(o.ey-o.y)+1}}
function render(){const p=composed(),scale=Math.max(4,Math.floor(512/state.w));cv.width=state.w*scale;cv.height=state.h*scale;ctx.fillStyle='#122033';ctx.fillRect(0,0,cv.width,cv.height);ctx.fillStyle='#d3fff0';p.forEach((v,i)=>{if(v)ctx.fillRect((i%state.w)*scale,Math.floor(i/state.w)*scale,scale,scale)});if($('grid').checked){ctx.strokeStyle='#334357';ctx.lineWidth=.6;ctx.beginPath();for(let x=0;x<=state.w;x++){ctx.moveTo(x*scale,0);ctx.lineTo(x*scale,cv.height)}for(let y=0;y<=state.h;y++){ctx.moveTo(0,y*scale);ctx.lineTo(cv.width,y*scale)}ctx.stroke()}
if(state.mode==='vector'&&selected>=0&&state.objects[selected]){const b=bounds(state.objects[selected]);ctx.strokeStyle='#f8bb59';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.strokeRect(b.x*scale,b.y*scale,b.w*scale,b.h*scale);ctx.setLineDash([])}if(keyboard){ctx.strokeStyle='#ffba55';ctx.lineWidth=2;ctx.strokeRect(cursor.x*scale,cursor.y*scale,scale,scale)}preview.fillStyle='#02080a';preview.fillRect(0,0,128,64);preview.fillStyle='#90eced';const ox=Math.floor((128-state.w)/2),oy=Math.floor((64-state.h)/2);p.forEach((v,i)=>{if(v)preview.fillRect(ox+i%state.w,oy+Math.floor(i/state.w),1,1)});$('lit').textContent=p.reduce((a,b)=>a+b,0)+' 點亮';$('bytes').textContent=Math.ceil(state.w/8)*state.h;$('dimensions').textContent=`${state.w} × ${state.h} PIXELS`;$('undo').disabled=!past.length;$('redo').disabled=!future.length;}
function textMetrics(text,size,g=document.createElement('canvas').getContext('2d')){g.font=`bold ${size}px "Microsoft JhengHei", "Noto Sans CJK TC", sans-serif`;g.textBaseline='alphabetic';const m=g.measureText(text),left=m.actualBoundingBoxLeft??0,ascent=m.actualBoundingBoxAscent??size,descent=m.actualBoundingBoxDescent??0;return{left,ascent,w:Math.max(1,Math.ceil(left+(m.actualBoundingBoxRight??m.width))),h:Math.max(1,Math.ceil(ascent+descent))}}
function textDraft(){return {type:'text',text:$('text').value,size:Number($('fontSize').value),x:0,y:0,ex:0,ey:0}}
function updateTextPreview(){const o=textDraft(),m=textMetrics(o.text,o.size),c=$('textPreview'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.fillStyle='#122033';g.fillRect(0,0,c.width,c.height);const p=Array(state.w*state.h).fill(0);o.x=Math.max(0,Math.floor((state.w-m.w)/2));o.y=Math.max(0,Math.floor((state.h-m.h)/2));rasterObject(p,o);const scale=Math.min((c.width-12)/state.w,(c.height-12)/state.h),ox=(c.width-state.w*scale)/2,oy=(c.height-state.h*scale)/2;g.fillStyle='#d3fff0';p.forEach((v,i)=>{if(v)g.fillRect(ox+i%state.w*scale,oy+Math.floor(i/state.w)*scale,scale,scale)});const fits=m.w<=state.w&&m.h<=state.h;$('addText').disabled=!o.text.trim()||!fits;$('textStatus').textContent=!o.text.trim()?'請輸入要加入的文字。':!fits?`文字需 ${m.w} × ${m.h} 像素，超出畫布；請縮小字級或加大畫布。`:`文字 ${m.w} × ${m.h} 像素，按下方按鈕加入。`;return{ o,m,fits }}
function addTextAt(position=null,record=true){const {o,m,fits}=updateTextPreview();if(!o.text.trim()){toast('請先輸入文字');return}if(!fits){toast('文字超出畫布，請縮小字級或加大畫布');return}o.x=position?Math.min(position.x,state.w-m.w):Math.floor((state.w-m.w)/2);o.y=position?Math.min(position.y,state.h-m.h):Math.floor((state.h-m.h)/2);o.ex=o.x;o.ey=o.y;if(record)snapshot();if(state.mode==='vector'){state.objects.push(o);selected=state.objects.length-1}else{flatten();rasterObject(state.pixels,o)}objectsUI();render();toast('文字已加入畫布，可按復原移除')}
function setTool(t){tool=t;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===t);b.setAttribute('aria-pressed',b.dataset.tool===t)});$('textSettings').hidden=t!=='text';$('toolHint').textContent={pencil:'點選或拖曳，點亮像素',eraser:'拖曳擦除像素',fill:'點選要填滿的區域',text:'按「加入文字」或點畫布指定位置',select:'選取圖形，再拖曳移動'}[t]||'按住拖曳，放開完成圖形';if(t==='text')updateTextPreview();}
function toolsUI(){const allowed=state.mode==='pixel'?['pencil','eraser','fill','line','rect','ellipse','text']:['select','line','rect','ellipse','text'];$('tools').replaceChildren(...allowed.map(t=>{const b=document.createElement('button');b.dataset.tool=t;b.innerHTML=`<span aria-hidden="true">${icons[t]}</span>${names[t]}`;b.onclick=()=>setTool(t);return b}));if(!allowed.includes(tool))tool=allowed[0];setTool(tool)}
function objectsUI(){$('objectsPanel').hidden=state.mode!=='vector';$('objects').replaceChildren(...state.objects.map((o,i)=>{let b=document.createElement('button');b.textContent=`${i+1} ${names[o.type]}`;b.classList.toggle('active',selected===i);b.onclick=()=>{selected=i;setTool('select');objectsUI();render()};return b}));$('deleteObject').disabled=selected<0;}
function sync(){$('width').value=state.w;$('height').value=state.h;const val=`${state.w},${state.h}`;$('preset').value=[...$('preset').options].some(o=>o.value===val)?val:'custom';for(const m of ['pixel','vector']){$(m).classList.toggle('active',state.mode===m);$(m).setAttribute('aria-pressed',state.mode===m)}toolsUI();objectsUI();render()}
function flatten(){if(state.objects.length){state.pixels=composed();state.objects=[];selected=-1;objectsUI();}}
function changeMode(m){if(state.mode===m)return;snapshot();state.mode=m;selected=-1;sync()}
function point(e){const r=cv.getBoundingClientRect();return{x:Math.max(0,Math.min(state.w-1,Math.floor((e.clientX-r.left)/r.width*state.w))),y:Math.max(0,Math.min(state.h-1,Math.floor((e.clientY-r.top)/r.height*state.h)))}}
function flood(x,y){const p=state.pixels,target=p[y*state.w+x];if(target===1)return;const stack=[[x,y]];while(stack.length){const [a,b]=stack.pop();if(a<0||a>=state.w||b<0||b>=state.h||p[b*state.w+a]!==target)continue;p[b*state.w+a]=1;stack.push([a-1,b],[a+1,b],[a,b-1],[a,b+1])}}
cv.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();cv.focus();keyboard=false;cv.setPointerCapture(e.pointerId);const p=point(e);cursor=p;if(tool==='select'){selected=-1;for(let i=state.objects.length-1;i>=0;i--){const b=bounds(state.objects[i]);if(p.x>=b.x-1&&p.x<=b.x+b.w&&p.y>=b.y-1&&p.y<=b.y+b.h){selected=i;break}}if(selected>=0){snapshot();drag={start:p,original:clone(state.objects[selected]),moving:true}}objectsUI();render();return}if(tool==='text'){addTextAt(p);return}snapshot();if(state.mode==='pixel')flatten();if(tool==='fill'){flood(p.x,p.y);render();return}drag={start:p,last:p,base:state.pixels.slice(),objectIndex:state.objects.length};if(['pencil','eraser'].includes(tool)){put(state.pixels,p.x,p.y,tool==='eraser'?0:1)}else if(state.mode==='vector'){state.objects.push({type:tool,x:p.x,y:p.y,ex:p.x,ey:p.y,filled:$('filled').checked});selected=drag.objectIndex}else rasterObject(state.pixels,{type:tool,x:p.x,y:p.y,ex:p.x,ey:p.y,filled:$('filled').checked});render()};
cv.onpointermove=e=>{const p=point(e);$('coords').textContent=`X ${p.x} / Y ${p.y}`;if(!drag)return;if(drag.moving){const o=drag.original,dx=p.x-drag.start.x,dy=p.y-drag.start.y;state.objects[selected]={...o,x:o.x+dx,y:o.y+dy,ex:o.ex+dx,ey:o.ey+dy}}else if(['pencil','eraser'].includes(tool)){line(state.pixels,drag.last.x,drag.last.y,p.x,p.y,tool==='eraser'?0:1);drag.last=p}else{const o={type:tool,x:drag.start.x,y:drag.start.y,ex:p.x,ey:p.y,filled:$('filled').checked};if(state.mode==='vector')state.objects[drag.objectIndex]=o;else{state.pixels=drag.base.slice();rasterObject(state.pixels,o)}}render()};
function endDrag(){drag=null;objectsUI();render()}cv.onpointerup=endDrag;cv.onpointercancel=endDrag;
cv.onkeydown=e=>{if(e.key.startsWith('Arrow')){e.preventDefault();keyboard=true;cursor.x=Math.max(0,Math.min(state.w-1,cursor.x+(e.key==='ArrowRight')-(e.key==='ArrowLeft')));cursor.y=Math.max(0,Math.min(state.h-1,cursor.y+(e.key==='ArrowDown')-(e.key==='ArrowUp')));$('coords').textContent=`X ${cursor.x} / Y ${cursor.y}`;render()}if(e.key===' '&&state.mode==='pixel'){e.preventDefault();snapshot();flatten();const i=cursor.y*state.w+cursor.x;state.pixels[i]=tool==='eraser'?0:1-state.pixels[i];render()}};
$('pixel').onclick=()=>changeMode('pixel');$('vector').onclick=()=>changeMode('vector');$('undo').onclick=()=>history(true);$('redo').onclick=()=>history(false);$('grid').onchange=render;
$('fontSize').oninput=()=>{$('fontValue').textContent=$('fontSize').value+' px';updateTextPreview()};
$('text').oninput=updateTextPreview;
$('addText').onclick=()=>addTextAt();
$('text').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();addTextAt()}});
$('preset').onchange=()=>{if($('preset').value!=='custom'){const [w,h]=$('preset').value.split(',');$('width').value=w;$('height').value=h}};
$('resize').onclick=()=>{const w=Number($('width').value),h=Number($('height').value);if(!Number.isInteger(w)||w<8||w>128||!Number.isInteger(h)||h<8||h>64){toast('寬度需為 8–128，高度需為 8–64 的整數');return}if(w===state.w&&h===state.h)return;if((w<state.w||h<state.h)&&!confirm('縮小畫布會裁掉超出範圍的內容，確定套用？'))return;snapshot();const p=composed(),old=state.w;state.pixels=Array(w*h).fill(0);for(let y=0;y<Math.min(h,state.h);y++)for(let x=0;x<Math.min(w,old);x++)state.pixels[y*w+x]=p[y*old+x];state.w=w;state.h=h;state.objects=[];selected=-1;cursor={x:0,y:0};sync();toast('已套用尺寸；原有圖形已轉為像素')};
$('invert').onclick=()=>{snapshot();flatten();state.pixels=state.pixels.map(v=>1-v);render()};$('flip').onclick=()=>{snapshot();flatten();const p=state.pixels.slice();state.pixels=p.map((_,i)=>p[Math.floor(i/state.w)*state.w+state.w-1-i%state.w]);render()};$('clear').onclick=()=>{if(confirm('確定清空畫布？之後仍可按復原。')){snapshot();state.pixels.fill(0);state.objects=[];selected=-1;objectsUI();render()}};$('deleteObject').onclick=()=>{if(selected<0)return;snapshot();state.objects.splice(selected,1);selected=-1;objectsUI();render()};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();history(!e.shiftKey)}else if(state.mode==='pixel'&&!e.ctrlKey&&!e.metaKey){if(e.key.toLowerCase()==='p')setTool('pencil');if(e.key.toLowerCase()==='e')setTool('eraser')}});
const filename=()=>$('name').value.trim().replace(/[^a-zA-Z0-9_\-\u3400-\u9fff]/g,'_').slice(0,60)||'oled_art';
function download(data,name,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function project(){return{format:'oled-classroom',version:1,name:$('name').value,...clone(state)}}
$('save').onclick=()=>{download(JSON.stringify(project(),null,2),filename()+'.json','application/json');toast('已下載作品，下次可匯入繼續編輯')};
$('png').onclick=()=>{const c=document.createElement('canvas');c.width=state.w;c.height=state.h;const g=c.getContext('2d');g.fillStyle='black';g.fillRect(0,0,state.w,state.h);g.fillStyle='white';composed().forEach((v,i)=>{if(v)g.fillRect(i%state.w,Math.floor(i/state.w),1,1)});c.toBlob(b=>{if(b)download(b,filename()+'.png','image/png')})};
function validate(d){if(!d||d.format!=='oled-classroom'||d.version!==1||!Number.isInteger(d.w)||!Number.isInteger(d.h)||d.w<8||d.w>128||d.h<8||d.h>64||!Array.isArray(d.pixels)||d.pixels.length!==d.w*d.h||!d.pixels.every(v=>v===0||v===1)||!Array.isArray(d.objects)||d.objects.length>1000||!['pixel','vector'].includes(d.mode))throw Error('檔案格式不符，請選擇本工具下載的 JSON 作品。');for(const o of d.objects){if(!['line','rect','ellipse','text'].includes(o.type)||!['x','y','ex','ey'].every(k=>Number.isInteger(o[k])&&Math.abs(o[k])<=512)|| (o.type==='text'&&(typeof o.text!=='string'||o.text.length>40||!Number.isInteger(o.size)||o.size<6||o.size>48)))throw Error('作品含有無效的圖形資料。')}return{w:d.w,h:d.h,pixels:d.pixels.slice(),objects:clone(d.objects),mode:d.mode}}
function loadProject(d){const next=validate(d);if(!confirm('載入作品會取代目前畫布，確定繼續？（可復原）'))return;snapshot();state=next;$('name').value=typeof d.name==='string'?d.name.slice(0,60):'oled_art';selected=-1;cursor={x:0,y:0};sync();toast('作品已載入')}
$('importBtn').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('作品檔案過大，請使用 2 MB 以下的 JSON。');loadProject(JSON.parse(await f.text()))}catch(err){toast(err instanceof SyntaxError?'無法讀取 JSON 檔案':err.message)}e.target.value=''};
let saved=[];try{const data=JSON.parse(localStorage.getItem('oled-classroom-gallery')||'[]');if(Array.isArray(data))saved=data.filter(d=>{try{validate(d);return true}catch{return false}}).slice(0,24)}catch{}
function gallery(){$('savedCount').textContent=saved.length;$('gallery').replaceChildren(...saved.map((d,i)=>{const row=document.createElement('div');row.className='saved';const b=document.createElement('button');b.textContent=d.name||'未命名作品';b.onclick=()=>loadProject(d);const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','刪除 '+(d.name||'作品'));del.onclick=()=>{if(!confirm('確定刪除這份装置內作品？'))return;const next=saved.filter((_,j)=>j!==i);try{localStorage.setItem('oled-classroom-gallery',JSON.stringify(next));saved=next;gallery()}catch{toast('無法存取裝置儲存空間')}};row.append(b,del);return row}))}
$('localSave').onclick=()=>{if(saved.length>=24){toast('最多保留 24 份，請下載備份後刪除舊作品');return}const next=[project(),...saved];try{localStorage.setItem('oled-classroom-gallery',JSON.stringify(next));saved=next;gallery();toast('已儲存在這台裝置')}catch{toast('無法儲存，請改用「下載可編輯作品」')}};
function bitmap(p,w,h){const b=[];for(let y=0;y<h;y++)for(let x=0;x<w;x+=8){let v=0;for(let bit=0;bit<8;bit++)if(x+bit<w&&p[y*w+x+bit])v|=1<<(7-bit);b.push(v)}return b}
function code(){const h=Number($('screen').value);if(state.h>h){$('code').value='目前畫布高度超過所選 OLED，請改用 128 × 64 或縮小畫布。';$('downloadCode').disabled=true;$('copyCode').disabled=true;return null}$('downloadCode').disabled=false;$('copyCode').disabled=false;const bytes=bitmap(composed(),state.w,state.h),rows=[];for(let i=0;i<bytes.length;i+=12)rows.push('  '+bytes.slice(i,i+12).map(v=>'0x'+v.toString(16).padStart(2,'0').toUpperCase()).join(', '));const text=`// Created with OLED 設計教室\n// Install Adafruit GFX Library and Adafruit SSD1306 in Arduino IDE.\n#include <Wire.h>\n#include <Adafruit_GFX.h>\n#include <Adafruit_SSD1306.h>\n\nAdafruit_SSD1306 display(128, ${h}, &Wire, -1);\nconst uint8_t artwork[] PROGMEM = {\n${rows.join(',\n')}\n};\n\nvoid setup() {\n  if (!display.begin(SSD1306_SWITCHCAPVCC, ${$('address').value})) {\n    for (;;) {}\n  }\n  display.clearDisplay();\n  display.drawBitmap(${Math.floor((128-state.w)/2)}, ${Math.floor((h-state.h)/2)}, artwork, ${state.w}, ${state.h}, SSD1306_WHITE);\n  display.display();\n}\n\nvoid loop() {}\n`;$('code').value=text;return text}
$('help').onclick=()=>$('helpDialog').showModal();$('exportBtn').onclick=()=>{code();$('exportDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('screen').onchange=code;$('address').onchange=code;$('downloadCode').onclick=()=>{const c=code();if(c)download(c,filename()+'.ino','text/plain')};$('copyCode').onclick=async()=>{const c=code();if(!c)return;try{await navigator.clipboard.writeText(c);toast('程式碼已複製')}catch{$('code').select();toast('請按 Ctrl / ⌘ + C 複製選取的程式碼')}};
sync();gallery();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_oled_design',description:'Read the current OLED design dimensions, mode, lit pixel count and bitmap bytes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');const p=composed();return{width:state.w,height:state.h,mode:state.mode,litPixels:p.reduce((a,b)=>a+b,0),bitmap:bitmap(p,state.w,state.h)}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}

function currentAIPrompt(){const pixels=composed();return createAIPrompt({name:$('name').value.trim()||'oled_art',width:state.w,height:state.h,pixels,bytes:bitmap(pixels,state.w,state.h),board:$('aiBoard').value,screenHeight:Number($('aiScreen').value),address:$('aiAddress').value,request:$('aiRequest').value})}
function refreshAI(){const prompt=currentAIPrompt();$('aiPrompt').value=prompt;return prompt}
function openAI() {refreshAI();$('aiDialog').showModal()}
async function copyAI(){const prompt=refreshAI();try{await navigator.clipboard.writeText(prompt);toast('AI 提示詞已複製，包含目前圖案資料')}catch{if(!$('aiDialog').open)$('aiDialog').showModal();$('aiPrompt').focus();$('aiPrompt').select();toast('請按 Ctrl / ⌘ + C，或長按選取內容複製提示詞')}}
function downloadAI(){download(refreshAI(),filename()+'_AI提示詞.txt','text/plain;charset=utf-8');toast('已下載 AI 提示詞 .txt')}
$('aiSettings').onclick=openAI;$('copyAI').onclick=copyAI;$('copyAIModal').onclick=copyAI;$('downloadAI').onclick=downloadAI;$('downloadAIModal').onclick=downloadAI;
for(const id of ['aiBoard','aiScreen','aiAddress','aiRequest'])$(id).addEventListener('input',refreshAI);
